@startuml

actor User
participant UIBFF
queue CommandBus
participant DomainModel
queue EventBus
participant Projectors
database ReadModels

User -> UIBFF : http commands
UIBFF -> CommandBus : commands
CommandBus -> DomainModel : commands
DomainModel -> EventBus : events
EventBus -> Projectors : events
Projectors -> ReadModels : write
User -> UIBFF : http queries
UIBFF -> ReadModels : read
ReadModels ->  UIBFF : results
UIBFF -> User : results

@enduml
